name: vrpro-segment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - tqdm
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
      - transformers>=4.44.0
      - timm
